name       : cloc
version    : 1.84
release    : 1
source     :
    - https://github.com/AlDanial/cloc/archive/1.84.tar.gz : b88a3adc669c15a9a32975095090708ba4eee5a73b8498369fae14be5b8a37d4
license    : GPL-2.0-or-later
component  : programming.tools
summary    : cloc counts blank lines, comment lines, and physical lines of source code in many programming languages
description: |
    cloc counts blank lines, comment lines, and physical lines of source code in many programming languages
builddeps  :
    - perl-algorithm-diff
    - perl-digest-md5
    - perl-parallel-forkmanager
    - perl-regexp-common
rundeps    :
    - perl-algorithm-diff
    - perl-digest-md5
    - perl-parallel-forkmanager
    - perl-regexp-common
install    : |
    cd Unix && %make_install
