name       : cloc
version    : '1.90'
release    : 3
source     :
    - https://github.com/AlDanial/cloc/archive/refs/tags/v1.90.tar.gz : 60b429dd2aa5cd65707b359dcbcbeb710c8e4db880886528ced0962c67e52548
license    : GPL-2.0-or-later
component  : programming.tools
homepage   : https://github.com/AlDanial/cloc/
summary    : Count lines of code in many programming languages
description: |
    cloc counts blank lines, comment lines, and physical lines of source code in many programming languages.
builddeps  :
    - perl-algorithm-diff
    - perl-digest-md5
    - perl-parallel-forkmanager
    - perl-regexp-common
rundeps    :
    - perl-algorithm-diff
    - perl-digest-md5
    - perl-parallel-forkmanager
    - perl-regexp-common
install    : |
    cd Unix
    %make_install
